apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: taskflow
  labels:
    app: user-service
    tier: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
        tier: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: user-service
        image: ghcr.io/blackshadow45/taskflow-platform/user-service:aa6aec825dd037b6c1653cca85e8f295f2117532
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5002
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 96Mi
          limits:
            cpu: 400m
            memory: 192Mi
        startupProbe:
          httpGet:
            path: /health
            port: 5002
          periodSeconds: 3
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          periodSeconds: 5
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: taskflow
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
  - name: http
    port: 5002
    targetPort: 5002